[package]
name = "project_euler_study_rust"
version = "0.1.0"
authors = ["Alexey M <alexeym@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
